kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30022
        hostPort: 3022
      - containerPort: 30000
        hostPort: 3000
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."host.docker.internal:5001"]
    endpoint = ["http://host.docker.internal:5001"]
  [plugins."io.containerd.grpc.v1.cri".registry.configs."host.docker.internal:5001".tls]
    insecure_skip_verify = true
  [plugins."io.containerd.grpc.v1.cri".registry.configs."host.docker.internal:5001".auth]
    username = ""
    password = ""


